version: '3'
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: linux_test
      MYSQL_USER: ti
      MYSQL_PASSWORD: secret
    ports:
      - 3307:3306
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge