version: '3'
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: linux_test
      MYSQL_USER: ti
      MYSQL_PASSWORD: secret
    ports:
      - 3307:3306
    networks:
      - app-tier

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      - app-tier
    entrypoint:
      "python /app/app.py"

networks:
  app-tier:
    driver: bridge